test_dataset:
  dataset:
    name: test-folder
    args:
      root_path: ./PIV-genImages/FlowData_test.list
      #uniform， backstep， cylinder， JHTDB， DNS_turbulence， SQG
      type: cylinder
  wrapper:
      name: sr-implicit-downsampled-fast
      args:
        scale_min: 1
        scale_max: 1
        inp_size: 256
  batch_size: 1
model_path: ./save/_train_PIV-genImages/epoch-best.pth
