test_dataset:
  dataset:
    name: test-folder
    args:
      root_path: ./problemclass2/FlowData_test.list
      #uniform， backstep， cylinder， JHTDB， DNS_turbulence， SQG
      type: backstep
  wrapper:
      name: sr-implicit-downsampled-fast
      args:
        scale_min: 2
        scale_max: 2
        inp_size: 64
  batch_size: 4
model_path: ./save/_train_PIV-Noise/epoch-best.pth

